### ISSUE TITLE
Segmentation fault  (core dumped)

### ISSUE THREAD

**Issue by Hexagram-King** [li3cmz/GRADE#1]
在运行 bash train.sh 时，老是报错 Segmentation fault      (core dumped)。不知道您在运行是否有该问题，如何解决的呢？

**Comment by li3cmz** [comment]
你好，猜测可能是你的环境没配置对，比如pytorch版本不对。各种库对应的版本在requirements.txt里~

**Comment by Hexagram-King** [comment]
> 你好，猜测可能是你的环境没配置对，比如pytorch版本不对。各种库对应的版本在requirements.txt里~

好的，谢谢你的回复。我再尝试下重新配置环境。

**Comment by Hexagram-King** [comment]
> 你好，猜测可能是你的环境没配置对，比如pytorch版本不对。各种库对应的版本在requirements.txt里~

好的，谢谢你的回复。我再尝试下重新配置环境。

**Comment by LiuChang97** [comment]
@li3cmz 这边也是，完全按照requirements来配置环境，也是Segmentation fault (core dumped)，能不能麻烦你看一下是不是有些包的版本号不对？或者有什么其他的注意事项呢？

**Comment by li3cmz** [comment]
> @li3cmz 这边也是，完全按照requirements来配置环境，也是Segmentation fault (core dumped)，能不能麻烦你看一下是不是有些包的版本号不对？或者有什么其他的注意事项呢？

你好，查找了一下，发现是texar依赖的sentencepiece的版本号不对，pip install sentencepiece==0.1.91 可解决问题
texar官方解释链接：[https://github.com/asyml/texar-pytorch/pull/328](url)

已更新requirements.txt。

**Comment by LiuChang97** [comment]
更新过就可以啦！非常感谢～
