### ISSUE TITLE
Where is the init_embd_file './tools/numberbatch-en-19.08.txt' ? And how is the file keyword.vocab generated?

### ISSUE THREAD

**Issue by LiuChang97** [li3cmz/GRADE#2]
Hi, I have some trouble running ./script/inference.sh . (using dailydialog dataset)
1. When running main_for_metric_grade.py, there is no such file: ./data/DailyDialog/keyword.vocab. How the file is generated?
2. When running main_for_metric_grade.py, there is no init_embd_file: ./tools/numberbatch-en-19.08.txt

**Comment by li3cmz** [comment]
Sorry for our misleading README, and we have updated it now.
About your questions:
1. For now, the "keyword.vocab"  file is in the  [processed training data](https://drive.google.com/file/d/1sj3Z_GZfYzrhmleWazA-QawhUEhlNmJd/view) and you need to download the provided data (or generate it from scratch) for inference. Thank you for pointing it out and we will fix it later.
2. "numberbatch-en-19.08.txt" is in the [tools](https://drive.google.com/file/d/1CaRhHnO0YsQHOnJsmMUJuL4w9HXJZQYw/view) we provided, please download and unzip it before using GRADE.

**Comment by LiuChang97** [comment]
Thanks! It's very helpful.

**Comment by LiuChang97** [comment]
Thanks a lot! That's very helpful.

**Comment by LiuChang97** [comment]
Thanks a lot! That's very helpful.

I have one more question. 
If I want to adopt GRADE to other dialog datasets such as ConvAI2, I wonder if I only need to generate three new files based on the new dataset
(1)original_dialog_merge.keyword, (2)original_dialog_merge.ctx_keyword, (3)original_dialog_merge.rep_keyword.
While the following files you provided in ./data/DailyDialog can be reused?
(1)the provided GRADE checkpoint, (2)keyword.vocab(3)dialog_keyword_tuples_multiGraph.hop, (4)1st_hop_nr10.embedding, (5)2nd_hop_nr10.embedding?

**Comment by LiuChang97** [comment]
Thanks a lot! That's very helpful.

I have one more question.
If I want to adopt GRADE to other dialog datasets such as ConvAI2, I wonder if I only need to generate 4 new files based on the new dataset
(1)original_dialog_merge.keyword, (2)original_dialog_merge.ctx_keyword, (3)original_dialog_merge.rep_keyword,(4)test_text.pkl.
While the following files you provided in ./data/DailyDialog can be reused?
(1)the provided GRADE checkpoint, (2)keyword.vocab(3)dialog_keyword_tuples_multiGraph.hop, (4)1st_hop_nr10.embedding, (5)2nd_hop_nr10.embedding?

**Comment by li3cmz** [comment]
> Thanks a lot! That's very helpful.
> 
> I have one more question.
> If I want to adopt GRADE to other dialog datasets such as ConvAI2, I wonder if I only need to generate 4 new files based on the new dataset
> (1)original_dialog_merge.keyword, (2)original_dialog_merge.ctx_keyword, (3)original_dialog_merge.rep_keyword,(4)test_text.pkl.
> While the following files you provided in ./data/DailyDialog can be reused?
> (1)the provided GRADE checkpoint, (2)keyword.vocab(3)dialog_keyword_tuples_multiGraph.hop, (4)1st_hop_nr10.embedding, (5)2nd_hop_nr10.embedding?


These 4 files are generated by running the "inference.sh" and you don't need to add extra code to generate them. What you need to do are to update the "load_dataset" function in "./preprocess/extract_keywords.py" and provide your own dataset in the specific format as described in the README.
