### ISSUE TITLE
cuda版本问题

### ISSUE THREAD

**Issue by 18166035475** [li3cmz/GRADE#4]
您好，是不是必须使用cuda 10.1呢，cpu上或者cuda11.1可以吗

**Comment by James-Yip** [comment]
您好，建议使用cuda10.1是因为我们实验时使用的是支持cuda10.1的pytorch版本，如果要使用cuda11.1的话，可以尝试更新到最新版本的pytorch。另外要在CPU上使用进行inference的话，需要删除掉代码中将model以及input移动到GPU的代码（建议还是使用GPU比较好）。
